services:
  attacker:
    command: bash -c 'apt-get update && apt-get install -y nmap curl iputils-ping
      && curl -L https://github.com/tsl0922/ttyd/releases/download/1.7.7/ttyd.aarch64
      -o /usr/local/bin/ttyd && chmod +x /usr/local/bin/ttyd && ttyd -W bash'
    image: kalilinux/kali-rolling:latest
    labels:
      traefik.docker.network: wadt-user5-tiredful-api-24120b_default
      traefik.enable: 'true'
      traefik.http.routers.wadt-user5-tiredful-api-24120b-terminal.entrypoints: web
      traefik.http.routers.wadt-user5-tiredful-api-24120b-terminal.rule: Host(`terminal.wadt-user5-tiredful-api-24120b.localhost`)
      traefik.http.services.wadt-user5-tiredful-api-24120b-terminal.loadbalancer.server.port: '7681'
    networks:
    - default
  web:
    image: tuxotron/tiredful-api
    labels:
      traefik.docker.network: wadt-user5-tiredful-api-24120b_default
      traefik.enable: 'true'
      traefik.http.routers.wadt-user5-tiredful-api-24120b.entrypoints: web
      traefik.http.routers.wadt-user5-tiredful-api-24120b.rule: Host(`wadt-user5-tiredful-api-24120b.localhost`)
      traefik.http.services.wadt-user5-tiredful-api-24120b.loadbalancer.server.port: '8000'
      wadt.user_id: '5'
    networks:
    - default
