services:
  attacker:
    command: bash -c 'apt-get update && apt-get install -y nmap curl iputils-ping
      && curl -L https://github.com/tsl0922/ttyd/releases/download/1.7.7/ttyd.aarch64
      -o /usr/local/bin/ttyd && chmod +x /usr/local/bin/ttyd && ttyd -W bash'
    image: kalilinux/kali-rolling:latest
    labels:
      traefik.docker.network: wadt-user5-shellshock-85b821_default
      traefik.enable: 'true'
      traefik.http.routers.wadt-user5-shellshock-85b821-terminal.entrypoints: web
      traefik.http.routers.wadt-user5-shellshock-85b821-terminal.rule: Host(`terminal.wadt-user5-shellshock-85b821.localhost`)
      traefik.http.services.wadt-user5-shellshock-85b821-terminal.loadbalancer.server.port: '7681'
    networks:
    - default
  web:
    image: vulnerables/cve-2014-6271
    labels:
      traefik.docker.network: wadt-user5-shellshock-85b821_default
      traefik.enable: 'true'
      traefik.http.routers.wadt-user5-shellshock-85b821.entrypoints: web
      traefik.http.routers.wadt-user5-shellshock-85b821.rule: Host(`wadt-user5-shellshock-85b821.localhost`)
      traefik.http.services.wadt-user5-shellshock-85b821.loadbalancer.server.port: '80'
      wadt.user_id: '5'
    networks:
    - default
