services:
  attacker:
    command: ttyd -W bash
    image: wadt-attacker:latest
    labels:
      traefik.docker.network: wadt-user7-grafana-d28677_default
      traefik.enable: 'true'
      traefik.http.routers.wadt-user7-grafana-d28677-terminal.entrypoints: web
      traefik.http.routers.wadt-user7-grafana-d28677-terminal.rule: Host(`terminal.wadt-user7-grafana-d28677.thedemo.fischbowl.tech`)
      traefik.http.services.wadt-user7-grafana-d28677-terminal.loadbalancer.server.port: '7681'
    networks:
    - default
  web:
    image: grafana/grafana:8.3.0
    labels:
      traefik.docker.network: wadt-user7-grafana-d28677_default
      traefik.enable: 'true'
      traefik.http.routers.wadt-user7-grafana-d28677.entrypoints: web
      traefik.http.routers.wadt-user7-grafana-d28677.rule: Host(`wadt-user7-grafana-d28677.thedemo.fischbowl.tech`)
      traefik.http.services.wadt-user7-grafana-d28677.loadbalancer.server.port: '3000'
      wadt.user_id: '7'
    networks:
    - default
