version: "3.8"

services:
  traefik:
    image: traefik:v3.6.2
    command:
      - "--log.level=DEBUG"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.file.filename=/etc/traefik/dynamic.yml"
      - "--providers.docker.network=wadt_sandbox_network"
      - "--providers.docker.exposedByDefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.traefik.address=:8080"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik/dynamic.yml:/etc/traefik/dynamic.yml:ro"
      - "/etc/letsencrypt:/etc/letsencrypt:ro"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - wadt_sandbox_network

  frontend:
    image: nginx:alpine
    volumes:
      - ./wadt-frontend/dist:/usr/share/nginx/html:ro
      - ./wadt-frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - wadt_sandbox_network

networks:
  wadt_sandbox_network:
    external: true
