# Generated by Django 5.2.7 on 2025-10-14 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Container",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("description", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREAT", "Created"),
                            ("RUN", "Running"),
                            ("RESTR", "Restarting"),
                            ("STOP", "Stopped"),
                            ("ERR", "Error"),
                        ],
                        max_length=30,
                    ),
                ),
                ("container_id", models.CharField(max_length=64)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contents", models.CharField(max_length=200)),
                ("timestamp", models.DateField(auto_now_add=True)),
                (
                    "container_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wadtapp.container",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="log_entry_user_id",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
