# Generated by Django 5.2.7 on 2025-10-15 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wadtapp", "0002_rename_user_id_container_user_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="container",
            old_name="container_id",
            new_name="docker_container_id",
        ),
    ]
