http:
  routers:
    api:
      rule: "(Host(`13.58.27.23`) || Host(`localhost`) || Host(`127.0.0.1`)) && PathPrefix(`/api`)"
      entryPoints:
        - web
      service: django-api
      priority: 100

    frontend:
      rule: "(Host(`13.58.27.23`) || Host(`localhost`) || Host(`127.0.0.1`)) && PathPrefix(`/`)"
      entryPoints:
        - web
      service: frontend-static
      priority: 1

  services:
    django-api:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:8000"

    frontend-static:
      loadBalancer:
        servers:
          - url: "http://web-app-deployment-tool-frontend-1:80"
