# Generated by Django 5.2.7 on 2025-10-14 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wadtapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="container",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="logentry",
            old_name="container_id",
            new_name="container",
        ),
        migrations.RenameField(
            model_name="logentry",
            old_name="user_id",
            new_name="user",
        ),
    ]
