# Generated by Django 5.2.7 on 2026-03-05 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wadtapp', '0003_rename_container_id_container_docker_container_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='container',
            name='status',
            field=models.CharField(choices=[('CREAT', 'created'), ('RUN', 'running'), ('RESTR', 'restarting'), ('STOP', 'stopped'), ('ERR', 'error')], max_length=30),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
