# Generated by Django 5.2.7 on 2026-03-05 04:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wadtapp', '0004_alter_container_description_alter_container_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='container',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_user_container_name'),
        ),
    ]
